name: weatheria
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.4
  font_awesome_flutter: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  msix: ^3.6.2

msix_config:
  display_name: Weatheria
  publisher_display_name: Platform instruments
  identity_name: com.example.weatherapp
  msix_version: 1.0.0.0
  logo_path: C:\Src\Flutter\weatherapp\photos\weather.png
  certificate_path: C:\Users\Cleverex\Documents\ANUROOP.pfx
  certificate_password: test

flutter:
  uses-material-design: true
